=== pendulum101/DigitalJournal/resources/data/journal.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT journal (entry*)>
<!ELEMENT entry (title, date, entryContents, mood)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT entryContents (#PCDATA)>
<!ELEMENT mood (#PCDATA)>
<!ATTLIST entry entryDate date >

=== pendulum101/DigitalJournal/resources/data/journal2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE journal SYSTEM "journal.dtd">
<journal>
    <entry>
        <title>A great day!</title>
        <date>23231</date>
        <entryContents>Today was a great day I hope there are many more like it</entryContents>
        <mood>2</mood>
    </entry>
    <entry>
        <title>Great it's working !</title>
        <date>23231</date>
        <entryContents>Today was a great day I hope there are many more like it</entryContents>
        <mood>2</mood>
    </entry>
</journal>
